### ISSUE TITLE
Creare feed RSS per le nuove issue di questo repo

### ISSUE THREAD

**Issue by aborruso** [spaghetti-open-data/raduno17#10]
Utile per la [richiesta](https://github.com/spaghetti-open-data/raduno17/issues/4#issuecomment-286555880) di @cirospat

**Comment by aborruso** [comment]
Eccolo http://feeds.feedburner.com/IssueOpenDataFest

**Comment by cirospat** [comment]
thanks so much @aborruso

**Comment by aborruso** [comment]
Non si aggiorna

**Comment by aborruso** [comment]
Ok, errore di me medesimo, corretto script :)
