### ISSUE TITLE
Proposta di hangout di progetto, domenica 19 alle 17

### ISSUE THREAD

**Issue by aborruso** [spaghetti-open-data/raduno17#11]
È una proposta di @dagoneye [qui](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/spaghettiopendata/nTWOs19fCcw/NXr3qKIWEwAJ).

**Comment by dagoneye** [comment]
@aborruso potremmo farla anche alle 18, così evitiamo di far arrestare @peppelamensa

**Comment by aborruso** [comment]
Ok, allora per le 18 con @peppelamensa e speriamo altri!

**Comment by aborruso** [comment]
Ecco l'URL https://hangouts.google.com/call/btfpkf2b5zfbfb4v6nmnijv3sme

Ci vediamo lì tra poco

**Comment by dagoneye** [comment]
ecco il recap:
https://docs.google.com/document/d/1G13E9rp5UhAuzVlNwsFuX3UICqKa1vTOluV6CtVGcz4/edit?usp=sharing
