### ISSUE TITLE
Predisporre info su siti per pernottamenti, trasporti da aeroporto e logistic

### ISSUE THREAD

**Issue by cirospat** [spaghetti-open-data/raduno17#12]
i partecipanti hanno bisogno - già da ora - di info su:
- dove dormire per prenotare
- trasporti da aeroporto CT per CL o da PA per CL e ritorno (sia in bus che per noleggio auto). Orari bus.
- un minimo di info utili su Caltanissetta

Nei ritagli di tempo libero, per giocare, e pensando alle necessità delle persone, e anche per strummintiare ("smanettare" in siciliano) con il nuovo google_site che è in material desing e ben si adatta agli smartphone, ho creato questo situccio come modello gestionale di fornitura di informazioni. 
Ovviamente è un esperimentuccio, quindi come tale prendetelo. 
E' ovvio che confluisce sul nuovo http://opendatafest.it/ 

eccolo
[https://sites.google.com/view/caltanissettaopendata2017](https://sites.google.com/view/caltanissettaopendata2017)

**Comment by peppelamensa** [comment]
Queste info saranno disponibili dalla settimana prossima, Ciro

Il 15 Mar 2017 06:57, "ciro" <notifications@github.com> ha scritto:

i partecipanti hanno bisogno - già da ora - di info su:

   - dove dormire per prenotare
   - trasporti da aeroporto CT per CL o da PA per CL e ritorno (sia in bus
   che per noleggio auto). Orari bus.
   - un minimo di info utili su Caltanissetta

Nei ritagli di tempo libero, per giocare, e pensando alle necessità delle
persone, e anche per strummintiare ("smanettare" in siciliano) con il nuovo
google_site che è in material desing e ben si adatta agli smartphone, ho
creato questo situccio come modello gestionale di fornitura di informazioni.
Ovviamente è un esperimentuccio, quindi come tale prendetelo.
E' ovvio che confluisce sul nuovo http://opendatafest.it/

eccolo
https://sites.google.com/view/caltanissettaopendata2017

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/spaghetti-open-data/raduno17/issues/12>, or mute the
thread

**Comment by cirospat** [comment]
l'esperimento (mio) è stato spento

**Comment by dagoneye** [comment]
@peppelamensa ora è la next step da fare :) Se vuoi abbozzare qualcosa nel [wiki](https://github.com/spaghetti-open-data/raduno17/wiki) su questo fai pure.

**Comment by peppelamensa** [comment]
Speravo di ricevere ieri le info più rilevanti, quelle relative all'uso del
"campus" (pernottamenti ed altro). Non dovessero arrivare domani, riporterò
comunque tutti gli altri dati che abbiamo sul resto.

Giuseppe

2017-03-26 15:42 GMT+02:00 Matteo Brunati <notifications@github.com>:

**Comment by peppelamensa** [comment]
@dagoneye comincio a fare una bozza con quello che ho, domani comunque dovrei completare

**Comment by peppelamensa** [comment]
La bozza è in progress sia nei contenuti che nel layout. Aggiungo le info man mano che giungono.

**Comment by dagoneye** [comment]
> La bozza è in progress sia nei contenuti che nel layout. Aggiungo le info man mano che giungono.

Perfetto, l'ho linkata anche dalla home del wiki. 
Teniamola in draft fino a che non è completa, poi la inseriamo nella landing e nel sito di SOD.

**Comment by cirospat** [comment]
sulla [mappa](http://umap.openstreetmap.fr/it/map/logistica-ed-accoglienza-odfest17-caltanissetta_135842) che è stata redatta da Giuseppe, credo dovrebbero essere aggiunti, immagino nei punti degli arrivi bus a CL, gli orari di partenza bus da Catania e arrivo a Calatanissetta, così che i partecipanti cominciano a programmare i voli su CT
#logistic

la mappa dovrebbe essere inserita sul portale opendatafest.it, in alto accanto a partecipa - Proponi

**Comment by peppelamensa** [comment]
Posso farlo stasera o domattina perché sono in auto in viaggio per tutta la
giornata, temo.
Ma nella pag Logistica e accoglienza è presente il link diretto agli orari
di cui parli Ciro

Il 04 Apr 2017 09:05, "ciro" <notifications@github.com> ha scritto:

**Comment by peppelamensa** [comment]
Penso che mettendo la mappa al suo posto, cioè in basso nella pag.
Logistica e accoglienza che contiene già l'apposito collegamento diretto
agli orari, le info siano complete.


Il 04 Apr 2017 10:23, "Giuseppe La Mensa" <g.lamensa@gmail.com> ha scritto:

Posso farlo stasera o domattina perché sono in auto in viaggio per tutta la
giornata, temo.
Ma nella pag Logistica e accoglienza è presente il link diretto agli orari
di cui parli Ciro

Il 04 Apr 2017 09:05, "ciro" <notifications@github.com> ha scritto:

**Comment by peppelamensa** [comment]
La programmazione dei voli deve prescindere perché, come scritto più volte
in email, i collegamenti dall'aeroporto per Caltanissetta sono ogni ora
circa

Il 04 Apr 2017 12:51, "Giuseppe La Mensa" <g.lamensa@gmail.com> ha scritto:

**Comment by cirospat** [comment]
almeno io nel portale opendatafest.it non vedo logistica
cmq tutte le info della logistica credo dovrebbero andare nel portale per
rendere la vita facile ai partecipanti



Il giorno 4 aprile 2017 12:59, peppelamensa <notifications@github.com> ha
scritto:

**Comment by aborruso** [comment]
2017-04-04 13:06 GMT+02:00 ciro <notifications@github.com>:

> almeno io nel portale opendatafest.it non vedo logistica
> cmq tutte le info della logistica credo dovrebbero andare nel portale per
> rendere la vita facile ai partecipanti
>

Sì, sì, concordiamo tutti :)

La pagina della logistica (in draft) è qui
https://github.com/spaghetti-open-data/raduno17/wiki/Logistica

Dopo pranzo vedo di mettere qualcosa sulla landing page

___________________

Andrea Borruso
website: http://blog.spaziogis.it
38° 7' 48" N, 13° 21' 9" E, EPSG:4326
___________________

"cercare e saper riconoscere chi e cosa,
 in mezzo all’inferno, non è inferno,
e farlo durare, e dargli spazio"

Italo Calvino

**Comment by aborruso** [comment]
Ho inserito la sezione "[Dove](http://opendatafest.it/#dove)"

**Comment by dagoneye** [comment]
Ottimo: vediamo se risulta chiara o se ad un certo punto serva integrarla tutta nella landing, dipenderà dai feedback. Sicuramente in una prima fase averla nel wiki velocizza le correzioni/integrazioni. La inserisco anche nel sito SOD oggi.

Secondo voi ad un certo punto sarà il caso di inserire una parte per segnalare eventuali car pooling/car sharing dall'aeroporto? Magari basta farlo tra un mesetto, a maggio.

**Comment by peppelamensa** [comment]
Ciao ragazzi e scusate l'assenza a tratti (ma subisco problemi sanitari, ultimamente).

Secondo me la pag Logistica è troppo nascosta (sono le prime info che uno vorrebbe vedere per capire se è si tratta di mission impossible o cosa fattibile), vedrei più un "Logistica" al posto del "Dove" nel menu e, comunque, che colleghi direttamente ad apposita sezione nella landing. O (se pensiamo sia troppo per una landing), ad una pagina apposita. 
In basso, sotto tutte le info della sezione/pagina sulla Logistica (che partono con l'Intro), metterei la mappa.

@dagoneye sì, ha senso inserire anche quelle info. Le cerco.

**Comment by aborruso** [comment]
Ciao Peppe,

2017-04-05 9:58 GMT+02:00 peppelamensa <notifications@github.com>:

> Secondo me la pag Logistica è troppo nascosta (sono le prime info che uno
> vorrebbe vedere per capire se è si tratta di mission impossible o una cosa
> fattibile), vedrei più un "Logistica" al posto del "Dove" nel menu e,
> comunque, che colleghi direttamente ad apposita sezione nella landing o (se
> pensiamo sia troppo per una landing) in una pagina apposita. In basso,
> sotto tutte le info della sezione/pagina sulla Logistica, che partono con
> l'Introduzione, e info della pagina, metterei la mappa a completamento.


ok, apro issue. È bene esploderle e non fare un unico grosso thread.

Vado



___________________

Andrea Borruso
website: http://blog.spaziogis.it
38° 7' 48" N, 13° 21' 9" E, EPSG:4326
___________________

"cercare e saper riconoscere chi e cosa,
 in mezzo all’inferno, non è inferno,
e farlo durare, e dargli spazio"

Italo Calvino

**Comment by cirospat** [comment]
sono d'accordo con Giuseppe
io partecipante interessato a opendatafest17 ho necessità di sapere già da
ora (due mesi prima), leggendolo immediatamente su opendatafest.it:

   1. orari bus da e per aeroporto di CT e di PA, per programmare voli
   aerei in orari tali da arrivare in orari comodi a CL.
   2. qualche azienda di noleggio auto all'aeroporto (link). Diversi
   noleggeranno auto. E diversi avranno anche interesse a condividere con
   altri la stessa auto, arrivando in aereo con orari vicini.
   3. car sharing service link di Palermo e Catania (se esiste a CT)
   4. b&b di Caltanissetta (nome, email, tel. costo, indirizzo)
   5. mappa di CL con punti di interesse (già inserita su opendatafest.it)
   6. bus urbani di Caltanissetta. Linee e fermate.

Almeno questo secondo me.  Mi metto sempre nei panni del partecipante che
necessita di queste info logistiche.

Una cosa ho notato stamattina: le pagine wiki di github non sono
responsive. Quindi una bella noia zoommare e andare a dx sx con il touch
dello smartphone. Secondo me tutta questa parte di info logistica dovrebbe
andare dentro opendatafest.it che si adatta al dispaly dello smartphone.

OT
secondo me tutto ciò che è inerente l'evento dovrebbe stare dentro
opendatafest.it senza rimandi a github.
Opinioni solo personali senza importanza ovviamente.

--------






Il giorno 5 aprile 2017 09:58, peppelamensa <notifications@github.com> ha
scritto:

**Comment by peppelamensa** [comment]
Concordo con Ciro riguardo la necessità di usare la landing anche perché responsive.

Ragazzi, potendo lo farei io subito, ma dal bunker in cui mi trovo non transitano neanche i raggi gamma, se non a tratti

**Comment by aborruso** [comment]
@peppelamensa  aggiunta pagina logistica separata http://opendatafest.it/logistica.html

**Comment by dagoneye** [comment]
@peppelamensa ora c'è anche nel sito SOD, per chi arriva da lì (as usual):
- [http://www.spaghettiopendata.org/page/opendatafest-2017/come-arrivare-e-logistica-di-opendatafest](http://www.spaghettiopendata.org/page/opendatafest-2017/come-arrivare-e-logistica-di-opendatafest)

**Comment by peppelamensa** [comment]
Grazie ragazzi. Io ancora per qualche giorno sarò a mezzo servizio, sono in
ospedale per mia madre per trauma improvviso ed intervento riuscito. Ma
avrò 8h di nanna negli ultimi 3gg e non vedo bene neanche lo schermo :)

G

Il 06 Apr 2017 07:50, "Matteo Brunati" <notifications@github.com> ha
scritto:
