### ISSUE TITLE
Come invitare gruppi/comunità (European Data Portal, GGD, etc.)

### ISSUE THREAD

**Issue by dagoneye** [spaghetti-open-data/raduno17#13]
Serve predisporre un documento di invito di base per facilitare l'invito di persone/gruppi e comunità.
Richiesta nata da @albertocottica in [questo thread](https://groups.google.com/d/msg/spaghettiopendata/nTWOs19fCcw/vXl7GUyYDgAJ).

**Comment by albertocottica** [comment]
Secondo me questo non si può standardizzare. Io chiedevo una landing page da linkare negli inviti. Ma non è urgente. 

European Data Portal mi ha risposto con interesse. Verificano se possono mandarci qualcuno.
