### ISSUE TITLE
Partner dell'evento: chi sono?

### ISSUE THREAD

**Issue by nelsonmau** [spaghetti-open-data/raduno17#14]
finora io so di opendata sicilia + spaghettiopendata

ce ne sono altri?

**Comment by aborruso** [comment]
Ciro Spataro aveva proposto di coinvolgere le altre comunità locali e dare valore al contributo di queste al tema degli open data, dedicandogli dei momenti della tre giorni. Ma al momento la cosa è ferma.
Ci sono da scrivere un po' di testi (Matteo ne ha indicati alcuni) per attivare un po' di cose, tra cui eventualmente questa.

**Comment by cristianolongo** [comment]
Ciao a noi di Hackspace Catania penso potrebbe interessare però sinceramente non so bene che contributo potremmo dare.

**Comment by nelsonmau** [comment]
@cristianolongo il contributo potrebbe essere che proponete un talk in cui raccontate tutte le cose fatte da voi sul territorio e i soggetti che avete coinvolto, non solo in ambito opendata

**Comment by davrusso** [comment]
L'Associazione Fare Nostrum disponibile a partecipare, vorremmo capire bene come...

**Comment by dagoneye** [comment]
@davrusso visto ora, scusa mi era proprio sfuggito. 
Siete ovviamente invitati a venire, se riuscite ancora ad esserci, così intanto ci si conosce reciprocamente, cosa ne dite?
