### ISSUE TITLE
Aggiungere licenza CC BY al footer della landing

### ISSUE THREAD

**Issue by dagoneye** [spaghetti-open-data/raduno17#18]
Ok?
https://creativecommons.org/licenses/by/4.0/deed.it

**Comment by nelsonmau** [comment]
fixed 9a18d318560c1af2d65fb5e7709d4d5b078ed696

**Comment by dagoneye** [comment]
update: @nelsonmau grazie, occhio che hai aggiornato il branch master, ma quello giusto per il sito è gh-pages.

**Comment by nelsonmau** [comment]
ok apro issue apposita
chiudiamo qui, grazie :)
