### ISSUE TITLE
Aggiungere al minisito una pagina di benvenuto in inglese 

### ISSUE THREAD

**Issue by albertocottica** [spaghetti-open-data/raduno17#19]
Provo a sfangarmela da solo. Domanda per @aborruso: devo creare un altro branch o lavoro su gh-pages?

**Comment by aborruso** [comment]
@albertocottica vai pure anche su gh-pages!

**Comment by albertocottica** [comment]
@aborruso finito. In locale va bene, ma GitHub dice "There were conflicting changes" e non mi fa fare il sync. Come mi regolo?

**Comment by albertocottica** [comment]
Come non detto, risolto. Chiudo.
