### ISSUE TITLE
Aggiungere il filtro OpenDataFest per trovare i partecipanti al raduno dalla pag. community

### ISSUE THREAD

**Issue by dagoneye** [spaghetti-open-data/raduno17#20]
Dalla pagina [http://www.spaghettiopendata.org/community](http://www.spaghettiopendata.org/community) il filtro a sx è ancora quello di SOD16: @paolomainardi riesci a inserire quello nuovo scrivendo "Partecipa a OpenDataFest"? 

Io non trovo dove metter le mani, drupal è un mondo :) 
Thanks

**Comment by nelsonmau** [comment]
ho fatto io, puoi fare un check @dagoneye ?

la vista da modificare è `/structure/views/view/sod_users_user_search/`

**Comment by dagoneye** [comment]
Grazie @nelsonmau ora funziona! Mi segno la vista per un'altra volta.
