### ISSUE TITLE
Gestione branches

### ISSUE THREAD

**Issue by nelsonmau** [spaghetti-open-data/raduno17#21]
@aborruso e @dagoneye abbiamo al momento i branches `master` e `gh-pages`. Ne facciamo uno solo? Tanto la pagina può essere visibile anche se sotto master...

**Comment by aborruso** [comment]
@nelsonmau @dagoneye  per me gh-pages è quello di rendering del sito, mentre master (ed eventuali altri) potrebbero essere di supporto ad altre cose utili per il raduno.

Ma qualsiasi modo va bene. Una volta che l'abbiamo scelto, lo si scrive nel readme

**Comment by nelsonmau** [comment]
ok perfetto per me! chiudo qui :)
