### ISSUE TITLE
Inserire sezione "Logistica" nel sito

### ISSUE THREAD

**Issue by aborruso** [spaghetti-open-data/raduno17#23]
Inserire la sezione [logistica](https://github.com/spaghetti-open-data/raduno17/wiki/Logistica) del wiki, nel sito:

- o nella landing page, da mettere prima della mappa;
- o in una pagina web dedicata.

Deve essere ben visibile anche nel menu, con la voce "Logistica".

**Comment by cirospat** [comment]
potrebbe stare in una pagina web dedicata, l'importante che "logistica" è visibile dal menù

**Comment by aborruso** [comment]
@cirospat c'è scritto sopra

> Deve essere ben visibile anche nel menu, con la voce "Logistica".

È scritto male?  :D

**Comment by cirospat** [comment]
è scritto bene.

![image](https://cloud.githubusercontent.com/assets/3757525/24698611/9a04a63a-19f1-11e7-8004-bfb920d864ba.png)
ma se deve stare in alto insieme agli altri link, Logistica non c'è.

![image](https://cloud.githubusercontent.com/assets/3757525/24698643/b8103004-19f1-11e7-8eef-72ef16d5bc16.png)
c'è qui, sotto la mappa.

Secondo me la logistica dovrebbe stare ben visibile (= cioè in alto accanto Partecipa, proponi, ....)
ma ripeto è solo il mio punto di vista.

**Comment by aborruso** [comment]
@cirospat ma infatti è una issue aperta :(

Sono d'accordo con il tuo punto di vista!

**Comment by aborruso** [comment]
Fatto http://opendatafest.it/logistica.html
