### ISSUE TITLE
Quali sessioni sono state fatte negli anni? Possono esserci spunti utili

### ISSUE THREAD

**Issue by dagoneye** [spaghetti-open-data/raduno17#24]
Magari è utile per i nuovi o per stimolare le idee avere un quadro di insieme delle sessioni proposte dalle comunità negli anni. Per i raduni di SOD ho raccolto in una tabella tutte le sessioni fatte nei tre momenti a scelta dei raduni: il venerdì pomeriggio, il sabato e la domenica.

- [http://www.spaghettiopendata.org/page/altri-raduni-cosa-abbiamo-fatto](http://www.spaghettiopendata.org/page/altri-raduni-cosa-abbiamo-fatto) 

Per ogni sessione c'è il nome di chi l'ha proposta, così si ha un'idea di chi contattare nel caso si volesse continuare o aggregare del lavoro passato. Ho evitato di inserire i link alle singole sessioni per ridurre la confusione tra sessioni passate e quelle del raduno del 2017.

**Comment by seralf** [comment]
ottimo!
si potrebbero aggiungere anche le proposte bocciate, se ce ne è traccia da
qualche parte, o comunque iniziare a tracciarle d'ora in poi: dei buoni
spunti potrebbero esserci anche lì

Il giorno 9 aprile 2017 15:42, Matteo Brunati <notifications@github.com> ha
scritto:

**Comment by seralf** [comment]
invece c'è traccia da qualche parte ancora dei partecipanti ai vari gruppi
di hackathon?

Il giorno 9 aprile 2017 15:46, Alfredo Serafini <seralf@gmail.com> ha
scritto:

**Comment by dagoneye** [comment]
@seralf: due cose. Non ricordo di proposte bocciate, ma annullate forse sì per mancanza di chi l'aveva proposta. 

I partecipanti alle singole track degli hackathon forse sono nelle sessioni, ma ovviamente sono pure ipotesi. Ricordo che nella pratica molte volte sono cambiati e non di poco, non so quanto possa servire. In ogni caso sono dettagli che potremo fare a parte, vorrei evitare che si faccia casino tra sessioni vecchie e nuove :)

**Comment by seralf** [comment]
si erano semplicemente domande aperte nell'ottica "già che ci siamo, se ci
sono i dati e non costa troppo". Tanto insomma per tracciare quanto di più
possibile, se non ti ricordi te figurati io :-)

grazie comunque del riordino!

Il giorno 10 aprile 2017 13:31, Matteo Brunati <notifications@github.com>
ha scritto:
