### ISSUE TITLE
Bio di Baya Remaoun

### ISSUE THREAD

**Issue by albertocottica** [spaghetti-open-data/raduno17#25]
Intanto la metto qui. C'è un posto dove metterlo poi nel sito?

Baya Remaoun is web and data manager at CORDIS, the European Commission's primary public repository and portal to disseminate information on EU-funded research projects and their results in the broadest sense.  The team at the EU Publications Office ensure that the full lifecycle of research projects is publically available, including interactive web applications, multilingual summaries and open data. She joined the team in 2012 after 12 years at the European Court of Auditors.

**Comment by dagoneye** [comment]
Nel frattempo la bio l'ho inserita [al di sotto del suo speech](http://www.spaghettiopendata.org/page/opendatafest-2017/il-programma-di-opendatafest), in plenaria. 

Vediamo di valorizzarla anche in opendatafest.it e  nelle news sull'evento che faremo girare.

**Comment by dagoneye** [comment]
Inserita anche nel [programma in opendatafest.it](http://opendatafest.it/index.html#programma).

**Comment by dagoneye** [comment]
Aggiunta anche la foto del profilo nella bio nella plenaria in opendatafest.it, così è più visibile.
