### ISSUE TITLE
Aggiornare il programma nel sito SOD e nella pagina del sito opendatafest.it

### ISSUE THREAD

**Issue by dagoneye** [spaghetti-open-data/raduno17#26]
Partiamo dalla [pagina interna del sito SOD](http://www.spaghettiopendata.org/page/opendatafest-2017/il-programma-di-opendatafest) e poi aggiorniamo il sito con una nuova sezione.

In questa fase non inseriamo i dettagli delle stanze e degli spazi, ma servirà aggiungerlo poi, anche come issue successiva per non perderne traccia: è un'informzione che ci serve solo pochi giorni prima dell'evento, tutto sommato.

**Comment by dagoneye** [comment]
Work in progress, oggi lo finisco:
[http://www.spaghettiopendata.org/page/opendatafest-2017/il-programma-di-opendatafest-divenire](http://www.spaghettiopendata.org/page/opendatafest-2017/il-programma-di-opendatafest-divenire)

Domanda per @albertocottica: la tua sessione del pomeriggio del venerdì immagino corrisponda a quella inserita in plenaria il mattino, no? Per cui la possiamo togliere come sessione di UnConference?

**Comment by dagoneye** [comment]
Ok direi che la pagina di base potrebbe andare:
[http://www.spaghettiopendata.org/page/opendatafest-2017/il-programma-di-opendatafest](http://www.spaghettiopendata.org/page/opendatafest-2017/il-programma-di-opendatafest)

Ho inserito tutte le sessioni, dateci un'occhio @peppelamensa @aborruso

**Comment by dagoneye** [comment]
Un paio di cose che ci mancano:
- dettagli sul come spostarsi nel pranzo del venerdì, dove andare, etc...
- indicare la logistica delle sale (_questo si può fare la settimana prima_)

Se vi torna lo inseriamo anche nel sito opendatafest.it

**Comment by peppelamensa** [comment]
@dagoneye @aborruso
Alla voce Pranzo, al posto di "Andremo in città, per cui dovremo uscire e spostarci, anche perché le attività del pomeriggio si terranno in un altro luogo.", potremo scrivere

"Andremo in centro storico, nella piazza principale ([Piazza Garibaldi](https://www.google.it/search?q=piazza+garibaldi+caltanissetta&client=firefox-b-ab&source=lnms&tbm=isch&sa=X&ved=0ahUKEwj-wsiT__jTAhWRZlAKHW0KBRgQ_AUICygC&biw=1366&bih=641)), per cui dovremo [spostarci in auto](https://www.google.it/maps/dir/Centro+Culturale+Polivalente+%22Michele+Abbate%22,+Via+Sant'Averna,+234,+93100+Caltanissetta+CL/Piazza+Giuseppe+Garibaldi,+93100+Caltanissetta+CL/@37.4841837,14.0520249,15z/data=!3m1!4b1!4m14!4m13!1m5!1m1!1s0x1310c286bdc5bc01:0x3d69c163b3ab97b1!2m2!1d14.0584545!2d37.4785266!1m5!1m1!1s0x1310c28d08302c99:0x47c68029a87f6895!2m2!1d14.0634739!2d37.4898822!3e0) o con la Linea 3 (in giallo nella [mappa](http://opendatafest.it/logistica.html)) del Tpl.
Da lì ci si sposterà entro le 14,40 [in auto verso il Cefpas](https://www.google.it/maps/dir/Piazza+Giuseppe+Garibaldi,+93100+Caltanissetta+CL/Cefpas,+Via+Giuseppe+Mul%C3%A8,+Caltanissetta,+CL/@37.4929084,14.0299171,14z/data=!3m1!4b1!4m13!4m12!1m5!1m1!1s0x1310c28d08302c99:0x47c68029a87f6895!2m2!1d14.0634739!2d37.4898822!1m5!1m1!1s0x1310c21367df4c07:0x2937cb7f46b9c8e8!2m2!1d14.0288311!2d37.4907088), sede delle attività pomeridiane, o tramite la Linea 4 (in verde nella [mappa](http://opendatafest.it/logistica.html))."

**Comment by dagoneye** [comment]
> "Andremo in centro storico, nella piazza principale (Piazza Garibaldi), per cui dovremo spostarci in auto o con la Linea 3 (in giallo nella mappa) del Tpl.
Da lì ci si sposterà entro le 14,40 in auto verso il Cefpas, sede delle attività pomeridiane, o tramite la Linea 4 (in verde nella mappa)."

fatto, ho inserito i link alla mappa nel sito SOD, a questo punto possiamo inserirla anche nel sito opendatafest.it. 

dubbio: per la plenaria sarà meglio capire chi fa cosa nella tavola rotonda iniziale e negli altri momenti, ma di questo ne parliamo in lista. 

@peppelamensa un dubbio quindi: quando parli di Tpl intendi le corse agli orari classici o intendi l'autobus di cui ci parlavi? Non mi è chiaro per quali tratte dovrebbe aiutarci quello extra...

**Comment by peppelamensa** [comment]
Quelle sono le normali linee del Trasporto pubblico locale. 
Quello/i extra dovrebbero essere di supporto nei momenti duri (dovessero verificarsi). Intendo nei casi in cui, per es., dovessimo trovarci in tanti a doverci spostare simultaneamente e la frequenza delle corse non fosse adeguata (nei we, ci sono meno corse). O per eventualità varie

**Comment by dagoneye** [comment]
ok ragazzi aggiornato anche il sito opendatafest.it (_pagina principale e pagina logistica_), inserito il programma deciso fino ad ora e inserito nel menù anche "Sostieni".

**Comment by dagoneye** [comment]
Ok, quindi detto che:
> Quelle sono le normali linee del Trasporto pubblico locale.
Quello/i extra dovrebbero essere di supporto nei momenti duri (dovessero verificarsi). Intendo nei casi in cui, per es., dovessimo trovarci in tanti a doverci spostare simultaneamente e la frequenza delle corse non fosse adeguata (nei we, ci sono meno corse). O per eventualità varie

Consideriamo che il momento critico maggiore (_e in cui saremo di più direi_) è il pranzo del venerdì. Qualsiasi sforamento a causa dei trasporti ci crea casini alle sessioni pomeridiane, quindi serve essere super-organizzati e senza margini di dubbio, per quanto possibile :)

Guardando [gli orari della linea 3](http://www.scattrasporti.net/products.html), la fermata da prendere è quella di "Via Niscemi 365" proprio davanti a dove siamo la mattina e scendere poi alla "Corso Vittorio Emanuele II 140". Gli orari della linea sembrano questi: 12.45 – 13.45, uno all'ora (è venerdì quindi è sicuro). Immagino l'orario indichi la partenza dal capolinea, quindi è del tutto indicativa rispetto alla singola fermata, no?

Quindi a questo punto **serve contare le auto che ci saranno** e capire al volo se bastano, con qualcuno che al massimo si appoggia al bus, oppure se sia necessario il mezzo apposito.

Idem poi per andare dal centro al CEFPAS.
La linea 4 pare abbia questo orario che ci potrebbe andare bene: 14.40 e salire alla fermata "Corso Vittorio Emanuele", per chi dovrà usare il bus.

Che dici @peppelamensa?

**Comment by peppelamensa** [comment]
Giuseppe La Mensa:
Hai detto tutto bene, Matteo. Proprio perché non intendo correre, e far correre, rischi di ritardi, avevo preso appuntamento coi sigg della Scat nei per martedì per accertarmi della veridicità degli orari delle fermate già in mio possesso.
Chiedere di sapere quante auto ci saranno, era in agenda per domani (sì, sono al mare anche 'sta domenica) :)

**Comment by dagoneye** [comment]
Ok, facciamo così: chiudo questa issue e poi quando hai aggiornamenti aggiungiamo i dettagli con una nuova issue a parte, magari che inserisca gli elementi utili nella pagina di logistica.
