### ISSUE TITLE
Ridirigere opendatafest.org su una pagina che funziona

### ISSUE THREAD

**Issue by albertocottica** [spaghetti-open-data/raduno17#27]
http://opendatafest.org è nostro? Dice "sito in costruzione". Pare brutto, tanto più che abbiamo http://www.spaghettiopendata.org/page/opendatafest-il-raduno-del-2017-benvenuto

**Comment by dagoneye** [comment]
ehm allora Alberto: faccio un recap.

Abbiamo il sito opendatafest.it (dove dobbiamo inserire il programma, lo so): è pensato per aiutarci a comunicare il raduno per chi non conosce SOD o OpendataSicilia.

Ma poi per tutta la gestione delle sessioni/iscrizioni, etc... ci siamo ovviamente appoggiati al rodato sito di SOD.

**Comment by dagoneye** [comment]
@albertocottica tra l'altro ti avevo citato nella issue #26

**Comment by peppelamensa** [comment]
Fatto
