### ISSUE TITLE
Scrivere report di #ODFest17

### ISSUE THREAD

**Issue by aborruso** [spaghetti-open-data/raduno17#30]
Mi piacerebbe scrivere un report, per poi farlo girare.

Ho creato un documento su [GDrive](https://docs.google.com/document/d/18SZyXBNmVEJVLPWTcAGZn2TmI41vJCkqmrsPqJULZuY/)

**Comment by dagoneye** [comment]
Ottima idea, lavoriamo sulle cose che hai appuntato: la cosa più difficile mi pare il commento al venerdì pomeriggio, ma proviamoci. .)

**Comment by dagoneye** [comment]
@aborruso cosa ne dici? Cosa ci manca? 
Direi la parte sulla regione Sicilia e la parte che linki al lavoro fatto sul GTFS, per il resto mi pare che ci siamo.
