### ISSUE TITLE
Dare evidenza su OpenDataSicilia del raduno

### ISSUE THREAD

**Issue by aborruso** [spaghetti-open-data/raduno17#4]

**Comment by cirospat** [comment]
esiste la possibilità che ad ogni issue creata qui in automatico si alimenti un thread, con hashtag predefinito, in ML di ODS ? 
Così da tenere informati i membri di ODS che non sono su Github.
Grazie

**Comment by cirospat** [comment]
grazie 10000000
utile per tutti 
offro una birra :-)

**Comment by nelsonmau** [comment]
ho messo anche foto header con date evento http://opendatasicilia.it/

chiudo issue qui
