### ISSUE TITLE
Predisporre landing page

### ISSUE THREAD

**Issue by aborruso** [spaghetti-open-data/raduno17#5]
Abbiamo creato il puntamento da opendatafest.it al [branch gh-pages](https://github.com/spaghetti-open-data/raduno17/tree/gh-pages).

L'idea è quella di usarlo come landing page per tutte le informazioni di base e per puntare a tutti gli spazi utili (pagine per le proposte di intervento, hackathon, didattica, gli url di eventuali repo, wiki, ecc.).

**Comment by dagoneye** [comment]
Dopo aver abbozzato un testo di base e il kit per la comunicazione, ecco la discussione per la raccolta di spunti per lavorare alla landing in lista SOD:
[https://groups.google.com/d/msg/spaghettiopendata/3-mf6jkTyPA/p1pk2I7FAwAJ](https://groups.google.com/d/msg/spaghettiopendata/3-mf6jkTyPA/p1pk2I7FAwAJ)

**Comment by aborruso** [comment]
Ho iniziato a mettere i primi pezzi online http://opendatafest.it/

@dagoneye buttaci per favore un occhio ;)

**Comment by dagoneye** [comment]
Wow parrebbe molto buona a prima vista :) verifico se ci siamo con il resto intanto

**Comment by dagoneye** [comment]
ho aggiornato la sezione "Partecipa" e "Proponi" con i link alla guida e a come fare per iscriversi. Dacci una controllata @aborruso. Ora il sito è ok, invio email funzionante!

**Comment by cirospat** [comment]
centrare meglio il segnalibro su #proponi nel sito web. Risulta **tagliato** il testo:

![image](https://cloud.githubusercontent.com/assets/3757525/24473927/396d5aae-14cb-11e7-8430-d5936427de57.png)

**Comment by dagoneye** [comment]
@cirospat l'ho resa una sezione, così non c'è quel problema.

**Comment by nelsonmau** [comment]
la issue è risolta, chiudiamola :)
eventualmente se ne possono aprire altre più specifiche
