### ISSUE TITLE
Supportare Open Data Fest: raccolta fondi?

### ISSUE THREAD

**Issue by aborruso** [spaghetti-open-data/raduno17#7]
L'anno scorso per il raduno siciliano del 2016 di Messina abbiamo raccolto (se non ricordo male) circa 2000 €, che abbiamo usato per i pranzi e per pagare le trasferte di alcuni ospiti.

Li abbiamo raccolti sfruttando un conto paypal e un conto corrente di un'associazione non profit. Abbiamo tenuto traccia della cosa e abbiamo rendicontato.

Una tre giorni come questa secondo me ha bisogno di sostegno. In modo libero, senza che sia necessario acquistare un "biglietto".

Attivare la cosa è semplice, ma vorrei che fosse una cosa condivisa tra più teste.

**Comment by dagoneye** [comment]
La parte di sponsorizzazione da parte di privati la inseriamo qui? Può rientrarci?

**Comment by peppelamensa** [comment]
Sì. 
Riguardo eventuali sponsorizzazioni, attendo di avere un quadro più preciso del programma per risentire chi si è mostrato interessato. 
Riguardo la possibilità di raccogliere donazioni online, ci siamo attivati e siamo in attesa di risposte.

**Comment by seralf** [comment]
ma avete pensato a un crowdfunding? (immagino di si, ma chiedo)  avrebbe il vantaggio che anche eventuali sponsor potrebbero comunque aiutare a raggiungere gli obiettivi sulla medesima piattaforma, e in maniera tracciata e trasparente :-)

**Comment by peppelamensa** [comment]
Sì, siamo in attesa di attivazione di un IBAN. A giorni, ormai, dovrebbero rilasciarlo.

**Comment by seralf** [comment]
ottimo! in caso provo a farlo girare ;-)

2017-04-10 15:04 GMT+02:00 peppelamensa <notifications@github.com>:

**Comment by dagoneye** [comment]
@peppelamensa hai novità?

**Comment by peppelamensa** [comment]
Sì, avevo erroneamente riaperto il gdoc e dato notizie lì, l'altro ieri. Scusate.
In sostanza, perduto nelle mille interlocuzioni con Paypal (che dovrei concludere oggi o domani), ho dimenticato di segnalare e di chiedervi di pubblicare l'Iban che Leva Digitale ha da un po'...
Vogliamo inserirlo direttamente nella sezione di riferimento (Sostieni), per aggiungere il rif a paypal solo quando questa emetterà la sentenza?

Comunque si faccia, eccolo:
IT 50 Q 05018 04600 000000242796

(Altri rif.: Associazione Leva Digitale, Viale Trieste n°55, 93100 Caltanissetta)

**Comment by dagoneye** [comment]
> Vogliamo inserirlo direttamente nella sezione di riferimento (Sostieni), per aggiungere il rif a paypal solo quando questa emetterà la sentenza?
Comunque si faccia, eccolo:
IT 50 Q 05018 04600 000000242796

ok, io direi di sì. lo inserisco asap, forse stasera se riesco

**Comment by dagoneye** [comment]
Ok, fatto: [ora la voce](https://github.com/spaghetti-open-data/raduno17/commit/06aba260efcd7c69669c6efbeb2874545c310d47) "Sostieni" è tornata visibile.
