### ISSUE TITLE
Inserire in HP luogo e data del raduno

### ISSUE THREAD

**Issue by nelsonmau** [spaghetti-open-data/raduno17#8]
ok fare landing, ma in attesa sarebbe il caso di scrivere due righe per dire cos'è, quando e dove :)

poi sotto, mettici tutti i cavalli che vuoi :P

**Comment by aborruso** [comment]
Andrea e camminiamo anche su due piedi :)

Il primo che può inizia a scrivere quanto dici.

Grazie

**Comment by nelsonmau** [comment]
fatto
Grazie a te o immenso :)
